# If you already have gitea docker file just copy and paste this part into it!!
version: "3"

networks:
    gitea:
        external: false

services:
 # This is already from gitea's docker-compose
  server: 
    image: gitea/gitea
    container_name: gitea
    environment:
        - USER_UID=1001 # Enter the UID found from previous command output
        - USER_GID=1001 # Enter the GID found from previous command output
        - GITEA__database__DB_TYPE=mysql
        - GITEA__database__HOST=db:3306
        - GITEA__database__NAME=gitea
        - GITEA__database__USER=gitea
        - GITEA__database__PASSWD=giteaaa
    restart: always
    networks:
        - gitea
    volumes:
        - ./data:/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - /home/git/.ssh/:/data/git/.ssh
    ports:
        - "127.0.0.1:3330:3000"
        - "127.0.0.1:2222:22"
    depends_on:
        - db

  db:
    image: mysql
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=gitea
        - MYSQL_USER=gitea
        - MYSQL_PASSWORD=giteaaa
        - MYSQL_DATABASE=gitea
    networks:
        - gitea
    volumes:
        - ./mysql:/var/lib/mysql


 # Paste this
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v0.15
    container_name: woodpecker-server
    restart: unless-stopped
    ports:
      - 127.0.0.1:8941:8000
    volumes:
      - ./data/server:/var/lib/woodpecker
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://woodpecker.esmailelbob.xyz
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL= #Gitea root domain
      - WOODPECKER_AGENT_SECRET= #Secret from blog https://containers.fan/posts/setup-gitea-with-woodpecker-ci/
      - WOODPECKER_GITEA_CLIENT= #Client app 
      - WOODPECKER_GITEA_SECRET= #client app secert
      - WOODPECKER_GITEA_SKIP_VERIFY=true
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 512m
    networks:
      - gitea

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v0.15
    container_name: woodpecker-agent
    command: agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=us3A89YTXmX/MlnN2U7NSe7YXLC8dWrib06i9XuWmPI=
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 512m
    networks:
      - gitea
